SELECT * FROM TB_PRODUTOS;

UPDATE tb_produtos SET embalagem = 'LATA' where produto='1037797';

UPDATE tb_produtos SET nome = 'Clean - 350ml - Laranja', tamanho = '350ml', preco_lista = 5.50 WHERE produto ='1037797';

SELECT * FROM tb_vendedores;

UPDATE TB_VENDEDORES SET PERCENTUAL_COMISSAO = 0.18 WHERE MATRICULA = '00233';

UPDATE TB_VENDEDORES SET PERCENTUAL_COMISSAO = 0.18 WHERE MATRICULA = '00400';

UPDATE TB_VENDEDORES SET PERCENTUAL_COMISSAO = 0.18 WHERE MATRICULA = '00414';